# Generated by Django 4.2.30 on 2026-05-21 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_rating', models.FloatField(default=0)),
                ('total_rating', models.IntegerField(default=0)),
                ('total_profile_views', models.IntegerField(default=0)),
                ('total_followers', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('total_feed_impression', models.IntegerField(default=0)),
                ('total_feed_click', models.IntegerField(default=0)),
                ('total_booking', models.IntegerField(default=0)),
                ('feed_score', models.FloatField(default=0)),
                ('is_online', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('search_score', models.FloatField(default=0)),
                ('recommendation_score', models.FloatField(default=0)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='profiles.doctor')),
            ],
        ),
    ]
