# Generated by Django 4.2.30 on 2026-08-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_blooddonor_lives_saved_count_doctorrating_review_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-created']},
        ),
    ]
