# Generated by Django 4.2.30 on 2026-08-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_doctor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostictest',
            name='criteria',
            field=models.TextField(blank=True, null=True),
        ),
    ]
