# Generated by Django 4.2.30 on 2026-08-13 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_diagnostictest_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorscheduling',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='profiles.hospital'),
        ),
        migrations.AddField(
            model_name='doctorscheduling',
            name='max_patients',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.CreateModel(
            name='DoctorDateSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_approved', models.BooleanField(default=False)),
                ('max_patients', models.PositiveIntegerField(default=30)),
                ('bookings_count', models.PositiveIntegerField(default=0)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_slots', to='profiles.doctorscheduling')),
            ],
            options={
                'unique_together': {('schedule', 'date')},
            },
        ),
        migrations.AddField(
            model_name='doctorbooking',
            name='date_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='profiles.doctordateslot'),
        ),
    ]
