# Generated by Django 4.2.30 on 2026-08-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_photos_fees_and_turnaround'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoreducation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoreducation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor/education/'),
        ),
        migrations.AddField(
            model_name='doctoreducation',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
