# Generated by Django 4.2.30 on 2026-08-23 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_doctoreducation_description_doctoreducation_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorbooking',
            name='appointment_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='doctordateslot',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorscheduling',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctorscheduling',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorscheduling',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('cancelled_by_doctor', 'Cancelled by Doctor')], default='pending', max_length=25),
        ),
        migrations.CreateModel(
            name='PracticeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('diagnostic_center', 'Diagnostic Center'), ('chamber', 'Chamber'), ('other', 'Other')], default='hospital', max_length=30)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_locations', to='profiles.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctorbooking',
            name='practice_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='profiles.practicelocation'),
        ),
        migrations.AddField(
            model_name='doctorscheduling',
            name='practice_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='profiles.practicelocation'),
        ),
    ]
