# Generated by Django 4.2.30 on 2026-05-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma separated tags', max_length=500, null=True),
        ),
    ]
