# Generated by Django 4.2.30 on 2026-05-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_groups_alter_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('regular', 'Regular'), ('ambulance', 'Ambulance'), ('pharmacy', 'Pharmacy'), ('diagnostic', 'Diagnostic'), ('blood_donor', 'Blood Donor')], default='regular', max_length=20),
        ),
    ]
