events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;

    upstream django_upstream {
        server web1:8011;
        server web2:8012;
        server web3:8013;
    }

    upstream frontend_upstream {
        server medihub_frontend:5173;
    }

    server {
        listen 80;
        server_name localhost mrtech.company www.mrtech.company _;

        location /static/ {
            alias /app/staticfiles/;
            try_files $uri =404;
        }

        location /media/ {
            alias /app/media/;
            try_files $uri =404;
        }

        location /api/ {
            proxy_pass http://django_upstream;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /admin/ {
            proxy_pass http://django_upstream;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location ~ ^/(authentication|profiles|posts|blogs|location|doctors|donors|ambulances|pharmacies|diagnostics|swagger)/ {
            proxy_pass http://django_upstream;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
            proxy_pass http://frontend_upstream;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}